<?php
$translate = Zend_Registry::get("translate");
$labelClass ="";
if($this->element->isRequired())$labelClass .="required";
?>
<div class="form-group <?php echo $labelClass; ?>">
    <?php echo $this->{$this->element->helper}
	    ($this->element->getName(), $this->element->getValue(), $this->element->getAttribs());
	?>
    <?php if ($this->element->hasErrors()) { ?>
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <h4>
                <i class="icon fa fa-ban"></i><?php echo $translate->_("Alert"); ?>
            </h4>
            <?php echo $this->formErrors($this->element->getMessages()); ?>
        </div>
	<?php }?>
</div>