<?php
$translate = Zend_Registry::get("translate");
$labelClass ="";
if($this->element->isRequired())$labelClass .="required";
?>
<div class="form-group <?php echo $labelClass; ?>">
    <?php if (strlen($this->element->getLabel()) > 0) { ?>
        <label class="control-label" for="<?php echo $this->element->getName(); ?>"><?php echo $this->element->getLabel(); ?></label>
    <?php }?>
    <?php
    echo $this->{$this->element->helper}($this->element->getName(), $this->element->getValue(), $this->element->getAttribs());
    ?>
</div>