<?php
$translate = Zend_Registry::get("translate");
$labelClass ="";
if($this->element->isRequired())$labelClass .="required";
$name = $this->element->getName();
$attrs = $this->element->getAttribs();
$options = $attrs['options'];
?>
<div class="checkbox">
      <input type="checkbox"
          value="<?php echo $options['checkedValue']; ?>" id="<?php echo $this->element->getId(); ?>"
          name="<?php echo $name; ?>" <?php if($this->element->isChecked())echo "checked=\"checked\""; else echo ""; ?>
          <?php if($attrs['disabled'] == "disabled" || $attrs['disabled'] == true)echo "disabled=\"disabled\""; else echo ""; ?>
          <?php if(isset($attrs['tabindex']))echo "tabindex=\"{$attrs['tabindex']}\""; else echo ""; ?>>
      <label>
        <?php echo $this->formLabel($this->element->getName(), $this->element->getLabel()); ?>
      </label>
    <input type="hidden" value="<?php echo $options['uncheckedValue']; ?>" id="<?php echo $this->element->getId(); ?>hid" name="<?php echo $name; ?>">
</div>