<?php
$translate = Zend_Registry::get("translate");
?>
<script type="text/javascript">
$(document).ready(function() {
	$('#form_list_players').submit(function(){
		$('input[type=submit]', this).addClass('disabled');
	});

    $("#form_list_players").find("select").change(function() {
        $('#form_list_players').submit();
    });
});
</script>

<form id="form_list_players" class="form-inline" action="<?php echo $this->escape($this->element->getAction()); ?>"
	method="<?php echo $this->escape($this->element->getMethod()); ?>">

    <div class="row" style="max-width: 500px;">
        <?php if(isset($this->element->FILTER_BY_STATUS))echo $this->element->FILTER_BY_STATUS; ?>
    </div>

    <div class="row" style="max-width: 500px;">
        <?php if(isset($this->element->FILTER_BY))echo $this->element->FILTER_BY; ?>
    </div>

    <div class="row" style="max-width: 500px;">
        <?php if(isset($this->element->PAGE))echo $this->element->PAGE; ?>
        <?php if(isset($this->element->LIMIT))echo $this->element->LIMIT; ?>
    </div>

    <div class="row" style="max-width: 500px;">
        <?php echo $this->element->GENERATE_REPORT; ?>
        <?php echo $this->element->PREVIOUS_PAGE; ?>
    </div>

</form>