<?php 
$translate = Zend_Registry::get("translate");
$lang = Zend_Registry::get("lang");
?>
<script type="text/javascript">
$(document).ready(function() {
	$('#PASSWORD').keyup(function(){
		$('#result').html(checkStrength($('#PASSWORD').val()));
	});	
	function checkStrength(password){    
	//initial strength
    var strength = 0;	
    //if the password length is less than 6, return message.
    if (password.length < 6) { 
		$('#result').removeClass();
		$('#result').addClass('text-red');
		return '<?php echo $translate->_('Too short password'); ?>';
	}    
    //length is ok, lets continue.	
	//if length is 8 characters or more, increase strength value
	if (password.length > 7) strength += 1;	
	//if password contains both lower and uppercase characters, increase strength value
	if (password.match(/([a-z].*[A-Z])|([A-Z].*[a-z])/))  strength += 1;	
	//if it has numbers and characters, increase strength value
	if (password.match(/([a-zA-Z])/) && password.match(/([0-9])/))  strength += 1;	
	//if it has one special character, increase strength value
    if (password.match(/([!,%,&,@,#,$,^,*,?,_,~])/))  strength += 1;	
	//if it has two special characters, increase strength value
    if (password.match(/(.*[!,%,&,@,#,$,^,*,?,_,~].*[!,%,&,@,#,$,^,*,?,_,~])/)) strength += 1;
	//now we have calculated strength value, we can return messages	
	//if value is less than 2
	if (strength < 2 ) {
		$('#result').removeClass();
		$('#result').addClass('text-red');
		return '<?php echo $translate->_('Weak password'); ?>';		
	} else if (strength == 2 ) {
		$('#result').removeClass();
		$('#result').addClass('text-yellow');
		return '<?php echo $translate->_('Good password'); ?>';	
	} else {
		$('#result').removeClass();
		$('#result').addClass('text-green');
		return '<?php echo $translate->_('Strong password'); ?>';
	}
}
	$("#PASSWORD").focus();
});
</script>
<br />
<form action="<?php echo $this->escape($this->element->getAction()); ?>"
	method="<?php echo $this->escape($this->element->getMethod()); ?>">
        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->element->NAME; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->element->PASSWORD; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <span id="result"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->element->CONFIRM_NEW_PASSWORD; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <span id="check"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3">
                <?php echo $this->element->SAVE; ?>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3">
                <?php echo $this->element->CANCEL; ?>
            </div>
        </div>
        <div class="row">
            <div class="hidden-elements">
                <?php echo $this->element->CSRF; ?>
            </div>
        </div>
</form>