<?php
$translate = Zend_Registry::get("translate");
$lang = Zend_Registry::get("lang");
$title = $translate->_("Browse");
$this->title = $title;
$this->headTitle($title);
require_once HELPERS_DIR . DS . 'ApplicationConstants.php';
require_once HELPERS_DIR . DS . 'NumberHelper.php';
require_once HELPERS_DIR . DS . 'StringHelper.php';
?>
<script type="text/javascript">

function filterPlayers() {
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("searchPlayersText");
  filter = input.value.toUpperCase();
  table = document.getElementById("table");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content-header">
        <span>
            <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'mobile-menu', 'action'=>'players'), null, true);?>" class="btn btn-warning btn-lg pull-right">
                <?php echo $translate->_("Back"); ?>
            </a>
            <br /><br />
        </span>
    </section>

    <section class="content-header">
        <h1>
            <?php
                echo $title;
            ?>
        </h1>
        <ol class="breadcrumb">
            <li><i class="fa fa-home"></i> <?php echo $translate->_("Players"); ?></li>
            <li class="active">
                <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players', 'action'=>'list-players'));?>">
                <?php echo $title; ?>
                </a>
            </li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group">
                        <?php echo $this->form; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-lg input-group-addon">
                                <i class="fa fa-search"></i>
                            </span>
                            <input type="text" id="searchPlayersText" class="input-lg form-control" style="max-width: 100%;" onkeyup="filterPlayers()" placeholder="<?php echo $translate->_("Filter"); ?>" autofocus />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <table id="table" class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr class="bg-blue-active">
                                <th>&nbsp;<?php echo $translate->_("Player Name"); ?>&nbsp;</th>
                                <th>&nbsp;<?php echo $translate->_("Player_Balance"); ?>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                foreach($this->paginator as $data) {
                            ?>
                                <tr class="cashier-tr">
                                    <td title="<?php echo $translate->_("Player Name"); ?>" class="cashier-td-column">
                                        <a class="btn btn-primary btn-block left-text-align" href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players', 'action'=>'details', 'player_id'=>$data['id']));?>" title="<?php echo $translate->_("ViewDetails"); ?>">
                                            <?php echo $this->escape($data['name']); ?>
                                        </a>
                                    </td>
                                    <td title="<?php echo $translate->_("Player_Balance"); ?>" align="right" class="cashier-td-column">
                                        <a class="btn btn-default btn-block noblockui right-text-align" href="javascript:void(0)">
                                            <?php echo NumberHelper::format_double($data['balance']); ?>
                                            <?php echo $data['start_time']; ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->