<?php
$translate = Zend_Registry::get("translate");
$lang = Zend_Registry::get("lang");
$head_title = $translate->_("Unlock Player");
$this->title = $head_title;
$this->headTitle($head_title);
?>

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                &nbsp;
                <span>
                    <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'terminal-players', 'action'=>'details', 'player_id'=>$this->player_id),null,true);?>" class="btn btn-warning btn-lg pull-right">
                        <?php echo $translate->_("Back"); ?>
                    </a>
                    <br /><br />
                </span>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-home"></i> <?php echo $translate->_("Terminal Players"); ?></li>
                <li class="active"><a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'terminal-players', 'action'=>'player-unlock', 'player_id'=>$this->player_id),null,true);?>"><?php echo $head_title; ?></a></li>
                <li class="active"><?php echo $this->username; ?></li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 pull-left">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">
                                <?php echo $head_title; ?>
                            </h3>
                        </div>
                        <div class="box-body">
                            <?php if(!strlen($this->message)==0){ ?>
                                <div class="alert alert-danger alert-dismissible">
                                    <h4>
                                        <i class="icon fa fa-ban"></i><?php echo $translate->_("Alert"); ?>
                                    </h4>
                                    <?php echo $this->message; ?>
                                </div>
                            <?php
                            }
                            ?>

                            <?php if(!strlen($this->information)==0){ ?>
                                <div class="alert alert-success alert-dismissible">
                                    <h4>
                                        <i class="icon fa fa-check"></i><?php echo $translate->_("Success"); ?>
                                    </h4>
                                    <?php echo $this->information; ?>
                                </div>
                            <?php
                            }
                            ?>

                            <?php
                                echo $this->form;
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        <!-- row -->
        </section>

    </div>