<?php 
$translate = Zend_Registry::get("translate");
$this->headScript()
->appendFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
echo $this->headScript();
?>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "modern",
        skin : "lightgray",
		plugins: [
		"advlist autolink hr lists link charmap anchor pagebreak",
		"searchreplace visualblocks wordcount emoticons textcolor",
		"insertdatetime table contextmenu paste code"
    	],
    	toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>
<script type="text/javascript">
$(document).ready(function() {
	if($("#AMOUNT")){
	var amountDefaultValue = $("#BALANCE_END").val();	
	$("#AMOUNT").keyup(function(){ 
		if($("#AMOUNT").val() == ""){
			$("#AMOUNT").val(amountDefaultValue);
		}
	});
	}
	$("#AMOUNT").numeric({ negative: false });
});
</script>
<form role="form" id="form_end_shift" action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>">
    <div class="container pull-left">
        <div class="row">
            <div class="col-xs-6">
                <?php if(isset($this->element->BALANCE_START)){ ?>
                <?php echo $this->element->BALANCE_START; ?>
                <?php } ?>
            </div>
            <div class="col-xs-6">
                <?php if(isset($this->element->START_SHIFT_TIME_S)){ ?>
                <?php echo $this->element->START_SHIFT_TIME_S; ?>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
                <?php if(isset($this->element->TOTAL_IN)){ ?>
                <?php echo $this->element->TOTAL_IN; ?>
                <?php } ?>
            </div>
            <div class="col-xs-6">
                <?php if(isset($this->element->START_SHIFT_TIME)){ ?>
                <?php echo $this->element->START_SHIFT_TIME; ?>
                <?php } ?>
            </div>
        </div>
         <div class="row">
            <div class="col-xs-6">
                <?php if(isset($this->element->TOTAL_OUT)){ ?>
                <?php echo $this->element->TOTAL_OUT; ?>
                <?php } ?>
            </div>
            <div class="col-xs-6">
                <?php if(isset($this->element->DURATION_TIME)){ ?>
                <?php echo $this->element->DURATION_TIME; ?>
                <?php } ?>
            </div>
        </div>
         <div class="row">
            <div class="col-xs-6">
                <?php if(isset($this->element->BALANCE_DIFF)){ ?>
                <?php echo $this->element->BALANCE_DIFF; ?>
                <?php } ?>
            </div>
             <div class="col-xs-6">
                <?php if(isset($this->element->AMOUNT)){ ?>
                <?php echo $this->element->AMOUNT; ?>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
                <?php if(isset($this->element->BALANCE_END)){ ?>
                <?php echo $this->element->BALANCE_END; ?>
                <?php } ?>
            </div>
            <div class="col-xs-6">
            </div>
        </div>
        <?php if(isset($this->element->COMMENT)){ ?>
        <div class="row">
            <div class="col-xs-12">
              <pre><?php echo $this->element->COMMENT; ?></pre>
            </div>
        </div>
        <?php } ?>
        <div class="row">
            <div class="col-xs-12">
              <?php echo $this->element->SAVE; ?>
                <div class="invincible">
                    <?php echo $this->element->CASH_IN_S; ?>
                    <?php echo $this->element->CASH_OUT_S; ?>
                    <?php echo $this->element->BALANCE_S; ?>
                    <?php echo $this->element->CASH_IN; ?>
                    <?php echo $this->element->CASH_OUT; ?>
                    <?php echo $this->element->CSRF; ?>
                </div>
            </div>
        </div>
    </div>
</form>