<?php
$translate = Zend_Registry::get("translate");
$lang = Zend_Registry::get("lang");
$head_title = $translate->_("PlayerPayoutCompleted");
$this->title = $head_title;
$this->headTitle($head_title);
?>

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

      <section class="content-header">

        <span>
            <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'financial-transaction', 'action'=>'withdraw-list'), null, true);?>" class="btn btn-warning btn-lg pull-right">
                <?php echo $translate->_("Back"); ?>
            </a>
            <br /><br />
        </span>

    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12 pull-left">
                <div class="box box-default">
                    <div class="box-body">
                        <?php if(!strlen($this->message)==0){ ?>
                            <div class="alert alert-danger alert-dismissible">
                                <h4>
                                    <i class="icon fa fa-ban"></i><?php echo $translate->_("Alert"); ?>
                                </h4>
                                <?php echo $this->message; ?>
                            </div>
                        <?php
                        }
                        ?>
                        <?php
                            echo $this->form;
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- row -->
    </section>
</div>