<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box box-danger">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-3">
                    &nbsp;
                </div>
                <div class="col-xs-8">
                    <br /> <br />
                    <h1>BackOffice has generated an error</h1>
                    <h3 style="color:black;"><?php echo $this->message ?></h3>
                    <a href="javascript:history.back()">Go to previous page</a>
                </div>
                <div class="col-xs-1">
                    &nbsp;
                </div>
            </div>
        </div>
        <!-- /.box-body -->
      </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->