<?php
require_once HELPERS_DIR . DS . 'ApplicationConstants.php';
$translate = Zend_Registry::get("translate");
$lang = Zend_Registry::get("lang");
$role = $_SESSION['auth_space']['session']['subject_type_name'];
?>

<nav class="navbar hidden-xs bg-blue-active" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
            <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players', 'action'=>'details', 'player_id'=>$this->details['player_id']), null, true);?>">
                <i class="fa fa-refresh"></i>
                <?php echo $translate->_("Player Details"); ?>
            </a>
        </li>

        <li>
          <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players-report', 'action'=>'game-sessions', 'player_id'=>$this->details['player_id']), null, true);?>" class="noblockui"role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bar-chart"></i>
              <?php echo $translate->_("ReportsListGameSessions"); ?>
          </a>
        </li>
        <li>
          <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players-report', 'action'=>'player-sessions', 'player_id'=>$this->details['player_id']), null, true);?>" class="noblockui" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bar-chart"></i>
              <?php echo $translate->_("Player Sessions"); ?>
          </a>
        </li>
        <li>
          <a href="<?php echo $this->url(array('lang'=>$lang, 'controller'=>'players-report', 'action'=>'credit-transfer', 'player_id'=>$this->details['player_id']), null, true);?>" class="noblockui" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bar-chart"></i>
              <?php echo $translate->_("ReportsListCreditTransfers"); ?>
          </a>
        </li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>